development:
  adapter: postgresql
  database: agile_life_dev
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: agile_life_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: agile_life
  user: <INSERT USER HERE>
  password: <INSERT PASSWORD HERE>
  pool: 5
  timeout: 5000